version: '3.5'

services:
  zookeeper:
    #Setting for M1 chip.
    platform: linux/x86_64
    #fixbug: no matching manifest for linux/arm64/v8 in the manifest list entries
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_m_broker
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka_network
    restart: always

  kafka:
    #Setting for M1 chip.
    platform: linux/x86_64
    #fixbug: no matching manifest for linux/arm64/v8 in the manifest list entries
    image: confluentinc/cp-kafka:latest
    container_name: kafka_m_broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_network
    restart: always

networks:
  kafka_network:
    driver: bridge