#This configuration file will hold common configs to be shared among all files
eureka:
    instance:
        prefer-ip-address: false
    client:
        serviceUrl:
            defaultZone: http://${REGISTER_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

security:
    oauth2:
        resource:
            user-info-uri: http://${REGISTER_HOST:localhost}:${HOME_SERVICES_HOST:8080}/uaa/user/current
            token-info-uri: http://${REGISTER_HOST:localhost}:${HOME_SERVICES_HOST:8080}/uaa/oauth/check_token

logging:
    level:
        org.springframework.security: DEBUG

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 20000